# ansible-galaxy install -r requirements.yml
---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "1.0.1"
    name: java
  - src: git@github.com:OlegAnanyev/elastic-role.git
    scm: git
    version: "1.0.2"
    name: elastic
  - src: git@github.com:OlegAnanyev/kibana-role.git
    scm: git
    version: "1.0.4"
    name: kibana